// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/biome-sh/biome-operator/pkg/apis/biome/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BiomeLister helps list Biomes.
type BiomeLister interface {
	// List lists all Biomes in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.Biome, err error)
	// Biomes returns an object that can list and get Biomes.
	Biomes(namespace string) BiomeNamespaceLister
	BiomeListerExpansion
}

// biomeLister implements the BiomeLister interface.
type biomeLister struct {
	indexer cache.Indexer
}

// NewBiomeLister returns a new BiomeLister.
func NewBiomeLister(indexer cache.Indexer) BiomeLister {
	return &biomeLister{indexer: indexer}
}

// List lists all Biomes in the indexer.
func (s *biomeLister) List(selector labels.Selector) (ret []*v1beta1.Biome, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Biome))
	})
	return ret, err
}

// Biomes returns an object that can list and get Biomes.
func (s *biomeLister) Biomes(namespace string) BiomeNamespaceLister {
	return biomeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BiomeNamespaceLister helps list and get Biomes.
type BiomeNamespaceLister interface {
	// List lists all Biomes in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1beta1.Biome, err error)
	// Get retrieves the Biome from the indexer for a given namespace and name.
	Get(name string) (*v1beta1.Biome, error)
	BiomeNamespaceListerExpansion
}

// biomeNamespaceLister implements the BiomeNamespaceLister
// interface.
type biomeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Biomes in the indexer for a given namespace.
func (s biomeNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.Biome, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Biome))
	})
	return ret, err
}

// Get retrieves the Biome from the indexer for a given namespace and name.
func (s biomeNamespaceLister) Get(name string) (*v1beta1.Biome, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("biome"), name)
	}
	return obj.(*v1beta1.Biome), nil
}
