// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/biome-sh/biome-operator/pkg/apis/biome/v1beta1"
	scheme "github.com/biome-sh/biome-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BiomesGetter has a method to return a BiomeInterface.
// A group's client should implement this interface.
type BiomesGetter interface {
	Biomes(namespace string) BiomeInterface
}

// BiomeInterface has methods to work with Biome resources.
type BiomeInterface interface {
	Create(*v1beta1.Biome) (*v1beta1.Biome, error)
	Update(*v1beta1.Biome) (*v1beta1.Biome, error)
	UpdateStatus(*v1beta1.Biome) (*v1beta1.Biome, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Biome, error)
	List(opts v1.ListOptions) (*v1beta1.BiomeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Biome, err error)
	BiomeExpansion
}

// biomes implements BiomeInterface
type biomes struct {
	client rest.Interface
	ns     string
}

// newBiomes returns a Biomes
func newBiomes(c *BiomeV1beta1Client, namespace string) *biomes {
	return &biomes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the biome, and returns the corresponding biome object, and an error if there is any.
func (c *biomes) Get(name string, options v1.GetOptions) (result *v1beta1.Biome, err error) {
	result = &v1beta1.Biome{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("biomes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Biomes that match those selectors.
func (c *biomes) List(opts v1.ListOptions) (result *v1beta1.BiomeList, err error) {
	result = &v1beta1.BiomeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("biomes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested biomes.
func (c *biomes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("biomes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a biome and creates it.  Returns the server's representation of the biome, and an error, if there is any.
func (c *biomes) Create(biome *v1beta1.Biome) (result *v1beta1.Biome, err error) {
	result = &v1beta1.Biome{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("biomes").
		Body(biome).
		Do().
		Into(result)
	return
}

// Update takes the representation of a biome and updates it. Returns the server's representation of the biome, and an error, if there is any.
func (c *biomes) Update(biome *v1beta1.Biome) (result *v1beta1.Biome, err error) {
	result = &v1beta1.Biome{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("biomes").
		Name(biome.Name).
		Body(biome).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *biomes) UpdateStatus(biome *v1beta1.Biome) (result *v1beta1.Biome, err error) {
	result = &v1beta1.Biome{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("biomes").
		Name(biome.Name).
		SubResource("status").
		Body(biome).
		Do().
		Into(result)
	return
}

// Delete takes name of the biome and deletes it. Returns an error if one occurs.
func (c *biomes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("biomes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *biomes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("biomes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched biome.
func (c *biomes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Biome, err error) {
	result = &v1beta1.Biome{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("biomes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
