// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	biomev1beta1 "github.com/biome-sh/biome-operator/pkg/apis/biome/v1beta1"
	versioned "github.com/biome-sh/biome-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/biome-sh/biome-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/biome-sh/biome-operator/pkg/client/listers/biome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BiomeInformer provides access to a shared informer and lister for
// Biomes.
type BiomeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.BiomeLister
}

type biomeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBiomeInformer constructs a new informer for Biome type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBiomeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBiomeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBiomeInformer constructs a new informer for Biome type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBiomeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiomeV1beta1().Biomes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiomeV1beta1().Biomes(namespace).Watch(options)
			},
		},
		&biomev1beta1.Biome{},
		resyncPeriod,
		indexers,
	)
}

func (f *biomeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBiomeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *biomeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&biomev1beta1.Biome{}, f.defaultInformer)
}

func (f *biomeInformer) Lister() v1beta1.BiomeLister {
	return v1beta1.NewBiomeLister(f.Informer().GetIndexer())
}
