apiVersion: v1
kind: ServiceAccount
metadata:
  name: biome-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: biome-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: biome-operator
subjects:
- kind: ServiceAccount
  name: biome-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: biome-operator
# Keep Cluster wide permissions at the top of the list and then update
# `TestRolesAndClusterRolesSync` in `test/sync/rbac` package to exclude
# those rules
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
- apiGroups:
  - biome.sh
  resources:
  - biomes
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch", "deletecollection"]
- apiGroups: [""]
  resources:
  - events
  verbs: [ "create", "patch" ]
