apiVersion: v1
kind: Secret
metadata:
  name: files-secret
type: Opaque
data:
  # base64 encoded string 'SecretPassword'
  pwfile: U2VjcmV0UGFzc3dvcmQK
---
apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: files-volume-biome
  labels:
    source: operator-example
    app: files-volume-biome
customVersion: v1beta2
spec:
  v1beta2:
    image: biome/redis-bio
    count: 1
    service:
      name: redis
      topology: standalone
      group: redisdb
      filesSecretName: files-secret
