// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/biome-sh/biome-operator/pkg/apis/biome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBiomes implements BiomeInterface
type FakeBiomes struct {
	Fake *FakeBiomeV1beta1
	ns   string
}

var biomesResource = schema.GroupVersionResource{Group: "biome.sh", Version: "v1beta1", Resource: "biomes"}

var biomesKind = schema.GroupVersionKind{Group: "biome.sh", Version: "v1beta1", Kind: "Biome"}

// Get takes name of the biome, and returns the corresponding biome object, and an error if there is any.
func (c *FakeBiomes) Get(name string, options v1.GetOptions) (result *v1beta1.Biome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(biomesResource, c.ns, name), &v1beta1.Biome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Biome), err
}

// List takes label and field selectors, and returns the list of Biomes that match those selectors.
func (c *FakeBiomes) List(opts v1.ListOptions) (result *v1beta1.BiomeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(biomesResource, biomesKind, c.ns, opts), &v1beta1.BiomeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BiomeList{ListMeta: obj.(*v1beta1.BiomeList).ListMeta}
	for _, item := range obj.(*v1beta1.BiomeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested biomes.
func (c *FakeBiomes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(biomesResource, c.ns, opts))

}

// Create takes the representation of a biome and creates it.  Returns the server's representation of the biome, and an error, if there is any.
func (c *FakeBiomes) Create(biome *v1beta1.Biome) (result *v1beta1.Biome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(biomesResource, c.ns, biome), &v1beta1.Biome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Biome), err
}

// Update takes the representation of a biome and updates it. Returns the server's representation of the biome, and an error, if there is any.
func (c *FakeBiomes) Update(biome *v1beta1.Biome) (result *v1beta1.Biome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(biomesResource, c.ns, biome), &v1beta1.Biome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Biome), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBiomes) UpdateStatus(biome *v1beta1.Biome) (*v1beta1.Biome, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(biomesResource, "status", c.ns, biome), &v1beta1.Biome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Biome), err
}

// Delete takes name of the biome and deletes it. Returns an error if one occurs.
func (c *FakeBiomes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(biomesResource, c.ns, name), &v1beta1.Biome{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBiomes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(biomesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.BiomeList{})
	return err
}

// Patch applies the patch and returns the patched biome.
func (c *FakeBiomes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Biome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(biomesResource, c.ns, name, data, subresources...), &v1beta1.Biome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Biome), err
}
