apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: example-namespaced-biome
  namespace: example-namespace
  labels:
    source: operator-example
    app: namespaced-biome
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis biome service packaged as a Docker image
    image: biome/redis-bio
    count: 1
    service:
      name: redis
      topology: standalone
      # if not present, defaults to "default"
      group: foobar
