apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: db
  labels:
    source: operator-example
    app: db
customVersion: v1beta2
spec:
  v1beta2:
    image: biome/redis-bio
    count: 1
    service:
      name: redis
      topology: standalone
---
apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: web-app
  labels:
    source: operator-example
    app: web-app
customVersion: v1beta2
spec:
  v1beta2:
    image: biome/bindgo-bio
    count: 1
    service:
      name: bio-server-go
      topology: standalone
      bind:
        # Name is the name of the bind specified in the Biome configuration files.
        - name: db
          # Service is the name of the service this bind refers to.
          service: redis
          # Group is the group of the service this bind refers to.
          group: default
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    biome-name: web-app
  type: NodePort
  ports:
  - name: web
    nodePort: 30001
    port: 5555
    protocol: TCP
