apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: example-standalone-biome
  labels:
    source: operator-example
    app: standalone-biome
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis biome service packaged as a Docker image
    image: biome/redis-bio
    count: 1
    service:
      name: redis
      topology: standalone
      # if not present, defaults to "default"
      group: foobar
