# This example deploys the operator on a cluster that has RBAC disabled.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: biome-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: biome-operator
    spec:
      containers:
      - name: biome-operator
        image: biomesh/biome-operator:v0.8.1
