{{- if .Values.operatorNamespaced }}
# Create this file only when the operator is meant to run in a namespace
# Since in a clusterwide setup operator itself would register a CRD
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: biomes.biome.sh
spec:
  group: biome.sh
  names:
    kind: Biome
    listKind: BiomeList
    plural: biomes
    shortNames:
    - bio
    singular: biome
  scope: Namespaced
  version: v1beta1
{{- end }}
