{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "biome-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "biome-operator.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else}}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
