apiVersion: v1
kind: Secret
metadata:
  # the name must mirror the ring filename, without the extension
  name: example-encrypted-ring-20170829113029
  labels:
    biome: "true"
    ring-key: "true"
type: Opaque
data:
  # base64-encoded ring key
  ring-key: U1lNLVNFQy0xCmV4YW1wbGUtZW5jcnlwdGVkLXJpbmctMjAxNzA4MjkxMTMwMjkKClFGZm9ZTHJOV3NNRk93Tk4wb0F1d3d4WjA1aVBMdTQxSUdGSzJISVFqTlk9
---
apiVersion: biome.sh/v1beta1
kind: Biome
metadata:
  name: example-encrypted-biome
  labels:
    source: operator-example
    app: encrypted-biome
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis biome service packaged as a Docker image
    image: biome/redis-bio
    count: 3
    service:
      name: redis
      topology: leader
      # the name of the secret containing the ring key
      ringSecretName: example-encrypted-ring-20170829113029
