apiVersion: v1
description: A Kubernetes controller that manages Biome services in a Kubernetes cluster.
engine: gotpl
maintainers:
  - name: Krzesimir Nowak
    email: krzesimir@kinvolk.io
  - name: Iago López Galeiras
    email: iago@kinvolk.io
  - name: Indradhanush Gupta
    email: indra@kinvolk.io
name: biome-operator
sources:
  - https://github.com/biome-sh/biome-operator
version: 0.8.1
